name: instagram_bottom_nav_bar
description: Best bottom bar structure created to control page flow.
version: 3.0.4
homepage: https://github.com/yusufnadar/instagram_bottom_nav_bar

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

