name: instagram_bottom_nav_bar
description: Best bottom bar structure created to control page flow. You don't need to describe navigatorKey for each Bottom Bar Item. I've already do that.
version: 3.0.13
homepage: https://github.com/yusufnadar/instagram_bottom_nav_bar

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg_provider: ^1.0.3
  flutter_svg: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

